### PR TITLE
ci: add check to enforce presence of license identifier

### PR DESCRIPTION
**Pull request by ingomueller-net**

### CODE REVIEW

**Comment by ingomueller-net** [comment]
The Github action doesn't work out of the box but I submitted enarx/spdx#24 and enarx/spdx#25 that should make it work.

**Review by jpienaar — APPROVED** [review]
Approved, but assuming we may have to delay until those other commits are accepted?

**Comment by ingomueller-net** [comment]
Yeah, exactly.

**Comment by jpienaar** [comment]
I see it worked and flagged some :)

**Pull request merged**
